version: '3.8'

services:
  luckybank-app:
    build:
      context: .  # путь к Dockerfile (текущая директория)
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/luckybank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 19111993
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: luckybank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19111993

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
