version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: luckybank
      POSTGRES_PASSWORD: password
      POSTGRES_DB: luckybank

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  luckybank-app:
    build: .
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/luckybank
      SPRING_DATASOURCE_USERNAME: luckybank
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_REDIS_HOST: redis  # Настройка хоста Redis
    depends_on:
      - db
      - rabbitmq
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"


#   docker-compose build       docker-compose up -d

